config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "dashboard#index"

  resources :service_types
  resources :services do 
    collection do 
      get 'customers' => 'services#show_customer_view', as: :only_customers
      get 'reportes'
    end
  end
  resources :customers
  resources :zones
  resources :debt_collectors
  resources :companies
  resources :usuarios

  get 'services/:id/planillapagos' => 'services#planilla_pagos', as: :planilla_de_pagos

  resources :dashboard do 
    collection do 
      get 'status' => 'dashboard#estados_de_cuenta'
    end
  end
  resources :fee_payments

  namespace :api do 
    
    post 'services/:id/baja' => 'services#baja'
    get 'services/my_services' => 'services#my_services'
    post 'services/fee_payment' => 'services#fee_payment'

    post 'users/login'
    resources :customers do 
      collection do 
        get 'search'
        get 'my_customers'
        get 'atrasos'
      end
    end
  end

end

app/models/service.rb
# == Schema Information
#
# Table name: services
#
#  id              :integer          not null, primary key
#  fecha           :date
#  monto           :decimal(, )
#  customer_id     :integer
#  descripcion     :string
#  comentarios     :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  service_type_id :integer
#  interes         :decimal(, )
#  periodo_pago    :string
#  baja            :boolean
#  comentario_baja :text
#

class Service < ActiveRecord::Base

  MENSUAL   = 'MENSUAL'
  SEMANAL   = 'SEMANAL'
  DIARIO    = 'DIARIO'
  QUINCENAL = 'QUINCENAL'


  PERIODOS_PAGOS = [MENSUAL, QUINCENAL, SEMANAL, DIARIO]

  belongs_to :service_type
  belongs_to :customer
  has_many :fees, -> {order(nro: :asc)}, dependent: :destroy
  validates_presence_of :fecha, :monto, :customer_id, :service_type_id
  validates_presence_of :periodo_pago
  validates_inclusion_of :periodo_pago, :in => PERIODOS_PAGOS
  
  def mensual?
    periodo_pago == MENSUAL
  end

  def monto_total
    monto.to_f * (interes.to_f + 1) 
  end

  def dar_de_baja(comentarios)
    self.baja = true
    self.comentario_baja = comentarios
    self.save!
  end

  def self.con_mas_de_x_cuotas_adeudadas(x)
    rows = Fee.connection.execute(%{
      SELECT service_id
      FROM fees
      WHERE vencimiento < now() AND ID NOT IN (
        SELECT fee_id 
        FROM fee_payments
      )
      GROUP BY service_id 
      HAVING count(id) >= #{x} ;
    })
    services = rows.map { |row|  Service.find(row['service_id']) }
    services.select { |s| !s.baja }
  end

  def hay_pagos_hechos?
    hay = false
    fees.each { |fee| 
      hay = hay || fee.pagado? 
    }
    hay
  end

  def dias_desde_ultimo_pago
    (Date.today - FeePayment.where(fee_id: fees.pluck(:id)).maximum(:fecha_pago)).to_i
  end

  def cuota_pendiente_actual
    fees.order(:nro => :asc).each { |fee|
      if fee.pagado == 0 && fee.con_saldo?
        return fee
      end
    }
    return nil
  end

  def adeudado
    (monto_total - pagado).round(2)
  end

  def credito_disponible
    fees.last.monto_establecido - fees.last.monto
  end

  def pagado
    pagado = 0
    fees.each { |fee|
      pagado += fee.pagado
    }
    pagado += credito_disponible
    pagado.round(2)
  end

  def cantidad_cuotas_vencidas
    fees_vencidas = []
    fees.each { |fee| 
       fees_vencidas << fee if fee.con_saldo? && fee.vencimiento < Date.today
    }
    fees_vencidas.count
  end

  def cantidad_cuotas_pendientes
    cantidad = 0
    fees.each { |fee| 
      cantidad += 1 if fee.con_saldo?
    }
    cantidad
  end

  def cantidad_cuotas_pagas
    fees.count - cantidad_cuotas_pendientes
  end

  #fees_params = {:periodo_pago, fees: [:nro_cuota, :monto]}
  def save_and_gen_fees(fees_params)
    self.periodo_pago = fees_params[:periodo_pago]
    self.interes = (interes / 100)
    self.baja = false
    save!
    fees.destroy_all
    fees_params[:fees].each_with_index { |fee_data, index|
      fecha_vencimiento = Date.today + (index + 1).weeks
      if (fees_params[:periodo_pago] == MENSUAL) 
        fecha_vencimiento = Date.today + (index + 1).months
      elsif fees_params[:periodo_pago] == DIARIO
        fecha_vencimiento = Date.today + (index + 1).days
      elsif fees_params[:periodo_pago] == QUINCENAL
        fecha_vencimiento = Date.today + ((index + 1) * 15).days
      end
      monto = fee_data[:monto] || self.monto / fees_params[:fees].count
      fee = Fee.find_by(service_id: self.id, nro: fee_data[:nro_cuota])
      if fee
        fee.monto = monto
        fee.monto_establecido = monto
        fee.vencimiento = fecha_vencimiento
        fee.save
      else
        fees << Fee.create(
          monto: monto, 
          monto_establecido: monto,
          nro: fee_data[:nro_cuota],
          vencimiento: fecha_vencimiento
          )
      end
    }
  end

  def to_s
    "#{customer.nombre_completo}, #{fecha.to_s}"
  end
end

app/models/service_type.rb
# == Schema Information
#
# Table name: service_types
#
#  id         :integer          not null, primary key
#  nombre     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  company_id :integer
#

class ServiceType < ActiveRecord::Base

  default_scope {order(nombre: :asc)}

  def to_s
    nombre
  end
end

app/controllers/api/services_controller.rb
class Api::ServicesController < Api::ApiController

  def baja
    @service = Service.find(params[:id])
    @service.dar_de_baja(params[:comentarios])
    render json: {message: 'Ok'}, status: :ok
  end

  def my_services
    @services = Service.includes(:customer).where(baja: false, customers: {debt_collector_id: params[:cobrador_id]})
    render json: @services, status: :ok
  end

  def fee_payment
    if params[:fee_payment][:monto].to_f != 0
      FeePayment.create_payments(fee_payment_params)
      render json: {message: 'Ok'}, status: :ok
    else
      render json: {message: 'Problemas'}, status: :unprocessable_entity
    end
  end

  private

    def fee_payment_params
      params.require(:fee_payment).permit(:id, :monto, :fee_id, :debt_collector_id, :comentarios, :fecha_pago)
    end
end

app/controllers/services_controller.rb
include ApplicationHelper
class ServicesController < ApplicationController

  before_action :fix_params_fecha_desde_hasta

  before_action :set_service, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!
  before_action :set_service_types, only: [:edit, :new]

  # GET /services
  # GET /services.json
  def index
    if current_user.cobrador?
      @services = Service.includes(:customer).where(customers: {debt_collector_id: current_user.cobrador.id})
    else
      @services = Service.includes(:customer).where(customers: {company_id: current_user.company_id})
    end
    if params[:dados_de_baja]
      @services = @services.where(baja: true)
    else
      @services = @services.where(baja: false)
    end
  end

  def planilla_pagos
    @service = Service.find(params[:id])
    path = Rails.root.join('tmp/' + SecureRandom.hex + '.xlsx')
    Axlsx::Package.new do |p|
      p.workbook.add_worksheet(:name => "Datos") do |sheet|
        sheet.add_row ['Cuota nro',
                       'Monto cuota', 
                       'Fecha pago', 
                       'Pago registrado el', 
                       'Pagado', 
                       'Comentarios']
        @service.fees.each do |fee|
          fee.fee_payments.each do |fp|
            sheet.add_row [ 
              fee.nro, 
              fee.monto.round(2), 
              fp.fecha_pago.to_s,
              l(fp.hora_pago, format: :short),
              fp.monto.round(2),
              fp.comentarios
            ]
          end
        end
      end
      p.serialize(path)
    end
    send_file path, filename: 'reporte.xlsx'
  end

  def reportes
    return unless params[:excel].present? 
    if params[:nro_servicio].present?
      @services = Service.includes(:customer).where(id: params[:nro_servicio], customers: {company_id: current_user.company_id})
    else
      @services = Service.includes(:customer).where(baja: false, customers: {company_id: current_user.company_id})
      @services = @services.where(fecha: params[:desde]..params[:hasta])
      if params[:cobrador_id].present?
        @services = @services.includes(:customer).where(baja: false, customers: {debt_collector_id: params[:cobrador_id]})
      end
      if params[:service_type_id].present?
        @services = @services.where(baja: false, service_type_id: params[:service_type_id])
      end
    end
    path = Rails.root.join('tmp/' + SecureRandom.hex + '.xlsx')
    Axlsx::Package.new do |p|
      p.workbook.add_worksheet(:name => "Datos") do |sheet|
        sheet.add_row ['Cliente', 
                       'DNI', 
                       'Tipo servicio', 
                       'Cobrador', 
                       'Número servicio', 
                       'Fecha', 
                       'Valor servicio', 
                       'Cant. cuotas', 
                       'Valor cuota',
                       'Cuotas pagas',
                       'Coutas pendientes',
                       'Fecha fin',
                       'Pagado',
                       'Adeuda']
        @services.each do |service|
          sheet.add_row [service.customer.to_s, 
            service.customer.dni, 
            service.service_type.nombre, 
            service.customer.debt_collector, 
            service.id, 
            service.fecha.to_s, 
            service.monto_total.round(2), 
            service.fees.count,
            service.fees.first.monto.round(2),
            service.cantidad_cuotas_pagas,
            service.cantidad_cuotas_pendientes,
            service.fees.last.vencimiento, 
            service.pagado.round(2), 
            service.adeudado.round(2)]
        end
      end
      p.serialize(path)
    end
    send_file path, filename: 'reporte.xlsx'
  end

  def show_customer_view
    if params[:token] != customers_token 
      render text: 'NO TIENE PERMISO PARA VER ESTA PÁGINA', status: :ok
    else
      if params[:dni].present?
        @customer = Customer.find_by_dni(params[:dni])
        @services = Service.includes(:customer).where(customers: {dni: params[:dni]})
        flash[:notice] = 'No se encontró este DNI la base de datos' if @customer.nil?
      end
      render :customer_view
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
    @cuotas = 3
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)
    respond_to do |format|
      if @service.save_and_gen_fees(fees_params)
        
        format.html { redirect_to services_path, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      @service.periodo_pago = fees_params[:periodo_pago]
      if @service.update(service_params)
        if @service.hay_pagos_hechos? == false
          @service.save_and_gen_fees(fees_params)
        end
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.dar_de_baja("")
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Servicio dado de baja' }
      format.json { head :no_content }
    end
  end

  private

    def fix_params_fecha_desde_hasta
      params[:desde] = '2010-01-01' if params[:desde].present? == false
      params[:hasta] = '2040-01-01' if params[:hasta].present? == false
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:fecha, :monto, :customer_id, :descripcion, :comentarios, :service_type_id, :interes)
    end

    def fees_params
      params.require(:fees_params).permit(:periodo_pago, fees: [:nro_cuota, :monto])
    end

    def set_service_types 
      @service_types = ServiceType.all.where(company_id: current_user.company_id)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= bootstrap_form_for(@service) do |f| %>
  <%= f.hidden_field :id %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <% if @service.persisted? %>
      <a data-toggle="modal" data-target="#modalbaja" id="baja-servicio" class="btn btn-danger pull-right" style="margin-right: 2em;margin-top: 2em">Dar de baja</a>
    <% end %>
    <div class="col-md-6">
      <div class="page-header">
        <h5 class="center">Datos </h5>
      </div>
      <%= f.date_field :fecha %>
      <%= f.select :service_type_id, ServiceType.all.collect {|d| [d.nombre, d.id]}, prompt: 'Seleccionar', label: 'Tipo de servicio', selected: (@service.service_type.id if @service.service_type) %>

      <label for="customer_id">Cliente no seleccionado</label> 
      <br>
      <a class="btn btn-default btn-sm" data-toggle="modal" data-target="#modal">Seleccionar cliente</a>
      <%= f.hidden_field :customer_id %>
      <br>
      <br>
      <%= f.number_field :monto, value: @service.monto, step: :any, disabled: @service.hay_pagos_hechos? %>
      <%= f.number_field :interes, value: @service.interes.to_f * 100, step: :any, disabled: @service.hay_pagos_hechos? %>
      <%= f.text_field 'monto_total', value: @service.monto_total, name: 'monto_total' %>
      <%= f.text_field :descripcion %>
      <%= f.text_field :comentarios %>
      <div class="form-group">
        <label for="">Última cuota</label>
        <% value = @service.fees.last ? @service.fees.last.vencimiento : nil %>
        <%= date_field 'fecha_fin_servicio', 'laal', class: 'form-control', disabled: true, value: value %>
      </div>

    </div>
    <div class="col-md-6">
      <div class="page-header">
          <h5 class="center">Forma de pago</h5>
      </div>
      <div class="form-group">
        <label for="fees_params[periodo_pago]">Periodo de pago</label>
        <% def_value = (params[:fees_params][:periodo_pago] if params[:fees_params]) || @service.periodo_pago %>
        <% options = options_for_select(Service::PERIODOS_PAGOS.map { |e| [e.capitalize, e]}, def_value) %>
        <%= select_tag("fees_params[periodo_pago]", options, 
            class: 'form-control', value: def_value) %>
      </div>
      <div class="form-group">
        <label for="cantidad_cuotas">Cantidad de cuotas</label>
        <input id="cantidad_cuotas" data-service-pagado="<%= @service.hay_pagos_hechos? %>" 
         name="cantidad_cuotas" type="number" class="form-control" value="<%= @service.fees.count %>">
      </div>
      <div class="row cuotas">
        <% @service.fees.each do |fee| %>
          <div class="col-md-6">
            <label for="fees_params[fees][][nro_cuota]">Cuota nro</label>
            <input name="fees_params[fees][][nro_cuota]" type="number" class="form-control" value="<%= fee.nro %>"> 
          </div> 
          <div class="col-md-6"> 
            <label for="fees_params[fees][][monto]">Monto</label>
            <input name="fees_params[fees][][monto]" type="number" class="form-control" value="<%= fee.monto %>">
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= f.submit "Guardar", class: 'btn-primary btn' %>

<% end %>

<div id="modalbaja" class="modal fade" role="dialog">

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Dar de baja servicio</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12">
            <label for="" class="label-control">Comentarios sobre la baja</label>
            <textarea  class="form-control" id="comentarios-baja" rows="3">
            </textarea>
            <br>
            <button id="confirmar-baja" class="btn btn-danger">Confirmar</button>
          </div>          
        </div>
      </div>

    </div>
  </div>
</div>
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Búsqueda de cliente</h4>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <input type="text" name="search" id="search" placeholder="Nombre, apellido, dirección" class="form-control">
        </div>
        <br>
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
                <tr>
                  <th>Nombre y apellido</th>
                  <th>Dirección</th>
                  <th>Cobrador</th>
                  <th>Selecc.</th>
                </tr>
            </thead>
            <tbody class="clientes">
              
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(function() {
    <% if (@service.hay_pagos_hechos?) %>
      $('#fees_params_periodo_pago').prop('disabled', 'disabled');
    <% end %>
  });
</script>

app/views/services/customer_view.html.erb
<div class="container">
  <div class="row">
  <h2 class="text-center">INGRESE SU DNI</h2>

  <%= bootstrap_form_tag(url: only_customers_services_path, method: :get) do |f| %>
    <%= f.hidden_field :token, value: params[:token] %>
    <%= f.text_field :dni %>
  <% end %>
  
  <% if notice %>
    <div class="alert alert-warning">
      <h5><%= notice %></h5>  
    </div>
  <% end %>
  

  <% if @services.present? && @services.any? %>
    <div class="row">
        <div class="col-lg-6 col-md-4">
            <div class="panel panel-green">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i>Servicios prestados</i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge"><%= @customer.services.count %></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-6 col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i>Cuotas pendientes</i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge"><%= @customer.cantidad_cuotas_pendientes %></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-6 col-md-4">
            <div class="panel panel-red">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i>Adeudado</i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge"><%= @customer.adeudado %></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <h3 class="text-center">Listado de servicios prestados</h3>

    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
      <thead>
        <tr>
          <th width="50px">Nro servicio</th>
          <th width="70px">Fecha</th>
          <th>Descripcion</th>
          <th>Monto</th>
          <th width="50px">Cuotas pagas</th>
          <th>Pagado</th>
          <th>Adeudado</th>
        </tr>
      </thead>

      <tbody>
        <% @services.to_a.sort {|x,y| y.adeudado <=> x.adeudado  }.each do |service| %>
          <tr class="odd gradeX">
            <td><%= service.id %></td>
            <td><%= service.fecha %></td>
            <td><%= service.descripcion %></td>
            <% pagado = service.pagado %>
            <td><h4><span class="label label-default"><%= service.monto_total %></span></h4></td>
            <td><h4><span ><%= service.cantidad_cuotas_pagas %></span></h4></td>
            <td><h4><span class="label label-success"><%= pagado %></span></h4></td>
            <td><h4><span class="label label-danger"><%= service.adeudado %></span></h4></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>  
</div>

app/views/services/edit.html.erb
<h1>Editar servicio</h1>

<%= render 'form' %>
<br>
<%= link_to 'Atrás', services_path, class: 'btn btn-default' %>

app/views/services/index.html.erb
<%= notice %>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">
          Listado de servicios
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
          <% if current_user.cobrador? == false %>
            <%= link_to 'Nuevo servicio', new_service_path, class: 'btn btn-primary', style: 'margin-bottom:1em' %>
            <%= link_to 'Mostrar servicios dados de baja', services_path(dados_de_baja: true), class: 'btn btn-danger pull-right', style: 'margin-bottom:1em' %>
          <% end %>

          <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
              <tr>
                <th>Nro servicio</th>
                <th>Fecha</th>
                <th>Fecha ult. cuota</th>
                <th>Cliente</th>
                <th>Descripcion</th>
                <th>Monto</th>
                <th>Pagado</th>
                <th>Adeudado</th>
                <th>Pago</th>
                <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @services.to_a.sort {|x,y| y.adeudado <=> x.adeudado  }.each do |service| %>
                <tr class="odd gradeX">
                  <td><%= service.id %></td>
                  <td><%= service.fecha %></td>
                  <td><%= service.fees.order(:nro => :asc).last.vencimiento %></td>
                  <td><%= service.customer %></td>
                  <td><%= service.descripcion %></td>
                  <% pagado = service.pagado %>
                  <td><h4><span class="label label-default"><%= service.monto %></span></h4></td>
                  <td><h4><span class="label label-success"><%= pagado %></span></h4></td>
                  <td><h4><span class="label label-danger"><%= service.adeudado %></span></h4></td>
                  <% sgte_cuota = service.cuota_pendiente_actual %>
                  <td>
                    <% if sgte_cuota && service.baja == false  %>
                      <%= link_to "Pago", new_fee_payment_path(params: {fee_id: sgte_cuota.id}), class: 'btn btn-success'%>
                    <% end %>
                  </td>
                  <td>
                    <a href="<%= service_path(service) %>" class="btn glyphicon glyphicon-eye-open"></a>
                  </td>
                  <td>
                    <% if service.baja == false %>
                      <a href="<%= edit_service_path(service) %>" class="btn glyphicon glyphicon-edit"></a>
                    <% end %>
                  </td>
                  <td>
                  <% if current_user.cobrador? == false %>
                    <%= link_to '', service, method: :delete, data: { confirm: 'Dar de baja el servicio?' }, class: "btn glyphicon glyphicon-remove glyphicon glyphicon-plus" %>
                  <% end %>
                    </td>
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>
</div>
<% if current_user.cobrador? == false %>
  <%= link_to 'Nuevo servicio', new_service_path, class: 'btn btn-primary' %>
<% end %>
<br>

app/views/services/new.html.erb
<%= render 'form' %>

<br>

<%= link_to 'Back', services_path, class: 'btn btn-default' %>

app/views/services/show.html.erb
<br>
<br>
<div class="row">
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i>Monto</i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><%= @service.monto_total %></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-4 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i>Pagado</i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><%= @service.pagado %></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-4 col-md-6">
        <div class="panel panel-red">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i>Adeudado</i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><%= @service.adeudado %></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row" style="height: 100%;">
    <div class="panel panel-default">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#datos">Datos</a></li>
            <li><a data-toggle="tab" href="#cuotas">Cuotas</a></li>
        </ul>
        <div class="tab-content">
            <div id="datos" class="tab-pane fade active in">
                <div class="panel-body">
                    <p>
                    <strong>Nro servicio:</strong>
                    <%= @service.id %>
                    </p>
                    <p>
                      <strong>Fecha:</strong>
                      <%= @service.fecha %>
                    </p>

                    <p>
                      <strong>Monto base:</strong>
                      <%= @service.monto %>
                    </p>

                    <p>
                      <strong>Monto total:</strong>
                      <%= @service.monto %>
                    </p>


                    <p>
                      <strong>Cantidad de cuotas:</strong>
                      <%= @service.fees.count %>
                    </p>

                    <p>
                      <strong>Interés:</strong>
                      <%= @service.interes %>%
                    </p>

                    <p>
                      <strong>Cliente:</strong>
                      <%= @service.customer %>
                    </p>

                    <p>
                      <strong>Periodo de pago:</strong>
                      <%= @service.periodo_pago.capitalize %>
                    </p>


                    <p>
                      <strong>Descripcion:</strong>
                      <%= @service.descripcion %>
                    </p>

                    <p>
                      <strong>Comentarios:</strong>
                      <%= @service.comentarios %>
                    </p>
                </div>
            </div>
            <div id="cuotas" class="tab-pane fade">
                <table width="100%" class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <td>Cuota nro</td>
                            <td>Cuota establ.</td>
                            <td>Cuota vari.</td>
                            <td>Vencimiento</td>
                            <td>Fecha pago</td>
                            <td>Hora pago</td>
                            <td>Pagado</td>
                            <td>Saldo +</td>
                            <td>Comentario pago</td>
                            <td>Pago</td>
                        </tr>                
                    </thead>
                    <tbody>
                        <% @service.fees.each do |fee|%>
                            <tr class="<%= "danger" if fee.vencimiento < Date.today %>">
                                <td><%= fee.nro %></td>
                                <td><%= fee.monto_establecido.round(2) %></td>
                                <td><%= fee.monto.round(2) %></td>
                                <td><%= fee.vencimiento %></td>
                                <td><%= fee.fechas_pagos %></td>
                                <td><%= fee.horas_pagos %></td>
                                <td><%= fee.pagado.round(2) %></td>
                                <td><%= (fee.monto_establecido - fee.monto).round(2) %></td>
                                <td><%= fee.comentarios_pagos %></td>
                                <% sgte_cuota = @service.cuota_pendiente_actual %>
                                <td>
                                    <% if fee == sgte_cuota && @service.baja == false  %>
                                            <%= link_to "Pago", new_fee_payment_path(params: {fee_id: fee.id}), class: 'btn btn-success'%>
                                    <% end %>
                                    <% if sgte_cuota and (sgte_cuota.nro  - 1 == fee.nro) and fee.fee_payments.last   %>
                                      <%= link_to "Editar pago", edit_fee_payment_path(fee.fee_payments.last), class: 'btn btn-success'%>

                                    <% end %>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
                <%= link_to 'Bajar planilla de pagos', planilla_de_pagos_path(@service.id), class: 'btn btn-success', style: 'width: 100%' %>
                    
            </div>
        </div>
    </div>
</div>
<% if current_user.cobrador? == false && @service.baja == false  %>
    <%= link_to 'Editar', edit_service_path(@service), class: 'btn btn-primary' %> 
<% end %>
<p></p>
<%= link_to 'Atrás', services_path, class: 'btn btn-default' %>