config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "dashboard#index"

  resources :service_types
  resources :services do 
    collection do 
      get 'customers' => 'services#show_customer_view', as: :only_customers
      get 'reportes'
    end
  end
  resources :customers
  resources :zones
  resources :debt_collectors
  resources :companies
  resources :usuarios

  get 'services/:id/planillapagos' => 'services#planilla_pagos', as: :planilla_de_pagos

  resources :dashboard do 
    collection do 
      get 'status' => 'dashboard#estados_de_cuenta'
    end
  end
  resources :fee_payments

  namespace :api do 
    
    post 'services/:id/baja' => 'services#baja'
    get 'services/my_services' => 'services#my_services'
    post 'services/fee_payment' => 'services#fee_payment'

    post 'users/login'
    resources :customers do 
      collection do 
        get 'search'
        get 'my_customers'
        get 'atrasos'
      end
    end
  end

end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id                :integer          not null, primary key
#  debt_collector_id :integer
#  nombre_completo   :string
#  dni               :string
#  telefono          :string(50)
#  otro_telefono     :string(50)
#  referencia        :string
#  comentarios       :text
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  direccion         :string
#  company_id        :integer
#

class Customer < ActiveRecord::Base
  belongs_to :debt_collector
  has_many :services
  has_many :customer_images

  accepts_nested_attributes_for :customer_images

  def self.search(q)
    return Customer.all if !q.present?
    Customer.where("nombre_completo ilike(:q) OR dni ilike(:q)", q: "%#{q}%" )
  end

  def self.con_mas_de_x_cuotas_adeudadas(x)
    Service.con_mas_de_x_cuotas_adeudadas(x).map { |s| s.customer }
  end

  def adeudado
    deuda = 0
    services.each { |ser|
      deuda += ser.adeudado
    }
    deuda.round(2)
  end

  def cantidad_cuotas_pendientes
    cantidad = 0
    services.each { |ser| 
      if ser.baja == false
        cantidad += ser.cantidad_cuotas_pendientes
      end
    }
    cantidad
  end

  def cantidad_cuotas_vencidas
    cantidad = 0
    services.each { |ser| 
      if ser.baja == false
        cantidad += ser.cantidad_cuotas_vencidas
      end
    }
    cantidad
  end

  def to_s
    nombre_completo
  end
end

app/controllers/api/customers_controller.rb
class Api::CustomersController < Api::ApiController

  def search
    @customers = Customer.search(params[:q]).where(company_id: current_user.company_id)
    render json: @customers, status: :ok, each_serializer: CustomerSearchSerializer
  end

  def my_customers
    @customers = Customer.where(debt_collector_id: params[:cobrador_id]).order(:nombre_completo)
    render json: @customers
  end

  def atrasos
    @customers = Customer.con_mas_de_x_cuotas_adeudadas(1).select { |c| c.debt_collector_id == params[:cobrador_id].to_i}
    render json: @customers
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all.where(company_id: current_user.company_id)
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    @customer.company_id = current_user.company_id
    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        @customer.update(company_id: current_user.company_id)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:debt_collector_id, :nombre_completo, :dni, :telefono, :otro_telefono, :referencia, :comentarios, :direccion, customer_images_attributes: [:image])
    end
end

app/helpers/api/customers_helper.rb
module Api::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<% if @customer.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

    <ul>
    <% @customer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= bootstrap_form_for(@customer, html: { multipart: true } ) do |f| %>
  <%= f.text_field :nombre_completo %>
  <%= f.text_field :dni %>
  <%= f.text_field :telefono %>
  <%= f.text_field :otro_telefono %>
  <%= f.select :debt_collector_id, DebtCollector.where(company_id: current_user.company_id).collect {|d| [d.apynom, d.id]}, prompt: 'Seleccionar', label: 'Cobrador', selected: @customer.debt_collector_id %>
  <%= f.text_field :direccion %>
  <%= f.text_field :referencia %>
  <%= f.text_area :comentarios, rows: 5 %>
  
  
  <input type="file" name="customer[customer_images_attributes][][image]">

  <br>
  <%= f.submit "Guardar", class: 'btn-primary btn' %>
<% end %>

app/views/customers/edit.html.erb
<h1>Editar cliente</h1>

<%= render 'form' %>

<br>

<%= link_to 'Show', @customer, class: 'btn btn-default' %> 
<%= link_to 'Back', customers_path, class: 'btn btn-default'  %>

app/views/customers/index.html.erb
<div class="row">
  <div class="col-lg-12">
      <h1 class="page-header">Clientes</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">
          Listado de clientes
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">

          <%= link_to 'Nuevo cliente', new_customer_path, class: 'btn btn-primary', style: 'margin-bottom:1em' %>
          <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
              <tr role="row">
                <th>Nro cliente</th>
                <th>Nombre completo</th>
                <th>Dni</th>
                <th>Telefono</th>
                <th>Direccion</th>
                <th>Cobrador</th>
                <th>Deuda</th>
                <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @customers.sort {|x,y| y.adeudado <=> x.adeudado }.each do |customer| %>
                <tr class="odd gradeX" role="row">
                  <td><%= customer.id %></td>
                  <td><%= customer.nombre_completo %></td>
                  <td><%= customer.dni %></td>
                  <td><%= customer.telefono %></td>
                  <td><%= customer.direccion %></td>
                  <td><%= customer.debt_collector %></td>
                  <td><%= customer.adeudado %></td>

                  <td>
                    <a href="<%= customer_path(customer) %>" class="btn glyphicon glyphicon-eye-open"></a>
                  </td>
                  <td>
                    <a href="<%= edit_customer_path(customer) %>" class="btn glyphicon glyphicon-edit"></a>
                  </td>
                  <td><%= link_to '', customer, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn glyphicon glyphicon-remove glyphicon glyphicon-plus" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Nuevo cliente', new_customer_path, class: 'btn btn-primary' %>

app/views/customers/new.html.erb
<h1>Nuevo cliente</h1>

<%= render 'form' %>
<br>
<%= link_to 'Volver', customers_path, class: 'btn btn-default' %>

app/views/customers/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <ul class="nav nav-tabs">
      <li class="active">
        <a href="#datos" data-toggle="tab" aria-expanded="true">Datos</a>
      </li>
      <li>
        <a href="#servicios" data-toggle="tab" aria-expanded="true">Servicios prestados</a>
      </li>
      <li>
        <a href="#estadocuenta" data-toggle="tab" aria-expanded="true">Estado de cuenta</a>
      </li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane fade active in" id="datos">
        <br>
        <p>
          <strong>Nro cliente:</strong>
          <%= @customer.id %>
        </p>
   
        <p>
          <strong>Dni:</strong>
          <%= @customer.dni %>
        </p>

        <p>
          <strong>Nombre completo:</strong>
          <%= @customer.nombre_completo %>
        </p>

        <p>
          <strong>Dirección:</strong>
          <a target="_blank" href="https://www.google.com.ar/maps/place/<%= @customer.direccion %>"><%= @customer.direccion %></a>
          
        </p>

        <p>
          <strong>Cobrador:</strong>
          <%= @customer.debt_collector %>
        </p>

     
        <p>
          <strong>Telefono:</strong>
          <%= @customer.telefono %>
        </p>

        <p>
          <strong>Otro telefono:</strong>
          <%= @customer.otro_telefono %>
        </p>

        <p>
          <strong>Referencia:</strong>
          <%= @customer.referencia %>
        </p>

        <p>
          <strong>Comentarios:</strong>
          <%= @customer.comentarios %>
        </p>


        <h4>Imagenes cargadas</h4>

        <% @customer.customer_images.each do |ci| %>
          <a href="<%= ci.image.url(:medium) %>">
            <%= image_tag ci.image.url(:medium), width: '100px', higth: '100px', class: 'imagen-customer' %>
          </a>
        <% end %>
        <br>
        <br>


        <%= link_to 'Editar', edit_customer_path(@customer), class: 'btn btn-primary' %> 
        <p></p>
        <%= link_to 'Atrás', customers_path, class: 'btn btn-default' %>        
      </div>
      <div class="tab-pane fade" id="servicios">
         <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
              <tr role="row">
                <th>Nro</th>
                <th>Fecha</th>
                <th>Descripcion</th>
                <th>Monto</th>
                <th>Pagado</th>
                <th>Adeudado</th>
              </tr>
            </thead>

            <tbody>
              <% @customer.services.to_a.sort {|x,y| y.adeudado <=> x.adeudado }.each do |service| %>
                <tr class="odd gradeX" role="row">
                  <td><%= service.id %></td>
                  <td><%= service.fecha %></td>
                  <td><%= service.descripcion %></td>
                  <td><h4><span class="label label-default"><%= service.monto_total %></span></h4></td>
                  <td><h4><span class="label label-success"><%= service.pagado %></span></h4></td>
                  <td><h4><span class="label label-danger"><%= service.adeudado %></span></h4></td>
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
      <div class="tab-pane fade" id="estadocuenta">
        <br>
        <br>
        <div class="row">
            <div class="col-lg-6 col-md-4">
                <div class="panel panel-green">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i>Servicios prestados</i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge"><%= @customer.services.count %></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-md-4">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i>Cuotas pendientes</i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge"><%= @customer.cantidad_cuotas_pendientes %></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-md-4">
                <div class="panel panel-red">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i>Adeudado</i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge"><%= @customer.adeudado %></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>


    </div>
  </div>
</div>