config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "dashboard#index"

  resources :service_types
  resources :services do 
    collection do 
      get 'customers' => 'services#show_customer_view', as: :only_customers
      get 'reportes'
    end
  end
  resources :customers
  resources :zones
  resources :debt_collectors
  resources :companies
  resources :usuarios

  get 'services/:id/planillapagos' => 'services#planilla_pagos', as: :planilla_de_pagos

  resources :dashboard do 
    collection do 
      get 'status' => 'dashboard#estados_de_cuenta'
    end
  end
  resources :fee_payments

  namespace :api do 
    
    post 'services/:id/baja' => 'services#baja'
    get 'services/my_services' => 'services#my_services'
    post 'services/fee_payment' => 'services#fee_payment'

    post 'users/login'
    resources :customers do 
      collection do 
        get 'search'
        get 'my_customers'
        get 'atrasos'
      end
    end
  end

end

app/models/zone.rb
# == Schema Information
#
# Table name: zones
#
#  id         :integer          not null, primary key
#  nombre     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Zone < ActiveRecord::Base

  def to_s
    nombre
  end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_action :set_zone, only: [:show, :edit, :update, :destroy]

  # GET /zones
  # GET /zones.json
  def index
    @zones = Zone.all
  end

  # GET /zones/1
  # GET /zones/1.json
  def show
  end

  # GET /zones/new
  def new
    @zone = Zone.new
  end

  # GET /zones/1/edit
  def edit
  end

  # POST /zones
  # POST /zones.json
  def create
    @zone = Zone.new(zone_params)

    respond_to do |format|
      if @zone.save
        format.html { redirect_to @zone, notice: 'Zone was successfully created.' }
        format.json { render :show, status: :created, location: @zone }
      else
        format.html { render :new }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zones/1
  # PATCH/PUT /zones/1.json
  def update
    respond_to do |format|
      if @zone.update(zone_params)
        format.html { redirect_to @zone, notice: 'Zone was successfully updated.' }
        format.json { render :show, status: :ok, location: @zone }
      else
        format.html { render :edit }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zones/1
  # DELETE /zones/1.json
  def destroy
    @zone.destroy
    respond_to do |format|
      format.html { redirect_to zones_url, notice: 'Zone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zone
      @zone = Zone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zone_params
      params.require(:zone).permit(:nombre)
    end
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/zones/_form.html.erb
<%= form_for(@zone) do |f| %>
  <% if @zone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zone.errors.count, "error") %> prohibited this zone from being saved:</h2>

      <ul>
      <% @zone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zones/edit.html.erb
<h1>Editing Zone</h1>

<%= render 'form' %>

<%= link_to 'Show', @zone %> |
<%= link_to 'Back', zones_path %>

app/views/zones/index.html.erb
<div class="row">
  <div class="col-lg-12">
      <h1 class="page-header">Zonas</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">
          Listado de zonas
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">

          <%= link_to 'Nueva zona', new_zone_path, class: 'btn btn-primary', style: 'margin-bottom:1em' %>
          <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
              <tr>
                <th>Nombre</th>
            
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @zones.each do |zone| %>
                <tr class="odd gradeX">
                  <td><%= zone.nombre %></td>
                  <td>
                    <a href="<%= zone_path(zone) %>" class="btn glyphicon glyphicon-eye-open"></a>
                  </td>
                  <td>
                    <a href="<%= edit_zone_path(zone) %>" class="btn glyphicon glyphicon-edit"></a>
                  </td>
                  <td><%= link_to '', zone, method: :delete, data: { confirm: 'Estás seguro?' }, class: "btn glyphicon glyphicon-remove glyphicon glyphicon-plus" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Nueva zona', new_zone_path, class: 'btn btn-primary' %>

app/views/zones/new.html.erb
<h1>New Zone</h1>

<%= render 'form' %>

<%= link_to 'Back', zones_path %>

app/views/zones/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @zone.nombre %>
</p>

<%= link_to 'Edit', edit_zone_path(@zone) %> |
<%= link_to 'Back', zones_path %>