config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "dashboard#index"

  resources :service_types
  resources :services do 
    collection do 
      get 'customers' => 'services#show_customer_view', as: :only_customers
      get 'reportes'
    end
  end
  resources :customers
  resources :zones
  resources :debt_collectors
  resources :companies
  resources :usuarios

  get 'services/:id/planillapagos' => 'services#planilla_pagos', as: :planilla_de_pagos

  resources :dashboard do 
    collection do 
      get 'status' => 'dashboard#estados_de_cuenta'
    end
  end
  resources :fee_payments

  namespace :api do 
    
    post 'services/:id/baja' => 'services#baja'
    get 'services/my_services' => 'services#my_services'
    post 'services/fee_payment' => 'services#fee_payment'

    post 'users/login'
    resources :customers do 
      collection do 
        get 'search'
        get 'my_customers'
        get 'atrasos'
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_locale

  before_action :authenticate_user!

  def set_locale
    I18n.locale = :es || I18n.default_locale
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def customers_token
    "a69487b528cf8d4e100c0fa3cbd3a878"
  end
end

app/views/application/_navigation_links.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= dashboard_index_path %>">Fenix cobranzas <%= "(#{current_user.company.nombre})" if current_user && current_user.company %></a>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="#"><i class="fa fa-user fa-fw"></i> <%= current_user.email %> (<%= current_user.tipo_usuario %>)</a>
                </li>
                <li class="divider"></li>
                <li><a href="<%= destroy_user_session_path %>" data-method="delete"><i class="fa fa-sign-out fa-fw"></i> Cerrar sesión</a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation" >
        <div class="sidebar-nav navbar-collapse" >
            <ul class="nav" id="side-menu" >
                <!--<li class="sidebar-search">
                    <div class="input-group custom-search-form">
                        <input type="text" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                    </div>
                </li>-->
                <% if current_user.admin_compania? %>
                    <li>
                        <a href="<%= dashboard_index_path %>"> Dashboard</a>
                    </li>

                    <li>
                        <a href="<%= customers_path %>">Clientes</a>
                    </li>
                    <li>
                        <a href="<%= services_path %>">Servicios</a>
                    </li>

                    <li>
                        <a href="<%= debt_collectors_path %>">Cobradores</a>
                    </li>

                    <li>
                        <a href="<%= reportes_services_path  %>">Reportes</a>
                    </li>

                    <li>
                        <a href="#">Configuración

                            <span class="fa margin-left arrow"></span>
                        </a>
                        <ul class="nav nav-second-level collapse">
                            <li>
                                <a href="<%= service_types_path %>">Tipos de servicios</a>
                            </li>

                            <li>
                                <a href="<%= usuarios_path %>">Usuarios</a>    
                            </li>
                        </ul>    
                    </li>
                    
                        
                <% end %>
                <% if current_user.cobrador? %>
                    <li>
                        <a href="<%= services_path %>">Servicios</a>
                    </li>
                <% end %>
                
                <% if current_user.admin? %>
                    <li>
                        <a href="<%= companies_path %>">Compañias</a>
                    </li>
                    <li>
                        <a href="<%= usuarios_path %>">Usuarios</a>
                        
                    </li>
                <% end %>

                <!--<li>
                    <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="flot.html">Flot Charts</a>
                        </li>
                        <li>
                            <a href="morris.html">Morris.js Charts</a>
                        </li>
                    </ul>
                </li>-->
                
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
  </nav>    